Catching device loop exception - need to shutdown device while VM running!
****** Loop 3
Caught: Inconsistent discovered device count: Native 3, callback 1
java.lang.InternalError: Inconsistent discovered device count: Native 3, callback 1
        at direct_bt.tinyb.DBTAdapter.removeDevices(DBTAdapter.java:280)
        at direct_bt.tinyb.DBTAdapter.startDiscovery(DBTAdapter.java:249)
        at ScannerTinyB01.main(ScannerTinyB01.java:194)

...

Exception thrown due to discoveredDevices differences of native / java side.
We may resolve this issue or allow such case.

However, we need to properly shutdown the native direct_bt
before the VM exits - otherwise we won't be able handle the lost Java references.
TODO: Add a java shutdown hook!